const developmentAssetPrefixes = ['/@fs/', '/src/', '/modules/', 'file:', 'blob:']

/**
 * Detects asset URLs generated by the local development server. These URLs
 * must not be persisted because they are unavailable in production builds.
 */
export const isDevelopmentAssetUrl = (url?: string): boolean => {
  if (!url) return false

  return developmentAssetPrefixes.some(prefix => url.startsWith(prefix))
    || /^[a-zA-Z]:[\\/]/.test(url)
}

export const resolvePersistedAssetUrl = (url: string | undefined, fallback: string): string => {
  return !url || isDevelopmentAssetUrl(url) ? fallback : url
}
