import { DEFAULT_THEME_COLOR, normalizeThemeColor } from '@/utils/theme-color'
import theme from '@theme-config'
import type { ThemeStyleCssVars, ThemeStyleToken } from '@/utils/theme-style'

const lightPrimaryColor = normalizeThemeColor(theme.colorPrimary) || DEFAULT_THEME_COLOR

type ThemeCssVarPalette = Record<
  | 'primary'
  | 'primarySoft'
  | 'primarySoftAlt'
  | 'primaryActive'
  | 'primary1'
  | 'primary2'
  | 'primary3'
  | 'primary4'
  | 'primary5'
  | 'brand50'
  | 'brand100'
  | 'brand200'
  | 'brand300'
  | 'brand400'
  | 'brand500'
  | 'brand600'
  | 'brand700'
  | 'brand800'
  | 'brand900'
  | 'primaryHover'
  | 'accentCyan'
  | 'accentBlue'
  | 'accentPink'
  | 'accentMagenta'
  | 'macaronOrangeBg'
  | 'macaronOrangeText'
  | 'macaronOrangeAvatar'
  | 'macaronBlueBg'
  | 'macaronBlueText'
  | 'macaronBlueAvatar'
  | 'macaronGreenBg'
  | 'macaronGreenText'
  | 'macaronGreenAvatar'
  | 'macaronPurpleBg'
  | 'macaronPurpleText'
  | 'macaronPurpleAvatar'
  | 'macaronPinkBg'
  | 'macaronPinkText'
  | 'macaronPinkAvatar'
  | 'macaronYellowBg'
  | 'macaronYellowText'
  | 'macaronYellowAvatar'
  | 'canvas'
  | 'bg'
  | 'bgElev'
  | 'bgSunken'
  | 'bgHover'
  | 'bg2'
  | 'line'
  | 'line2'
  | 'lineStrong'
  | 'text'
  | 'textSecondary'
  | 'textDisabled'
  | 'ink5'
  | 'accentInk'
  | 'danger'
  | 'dangerBg'
  | 'warning'
  | 'warningBg'
  | 'success'
  | 'successBg'
  | 'okLine'
  | 'warnLine'
  | 'errLine'
  | 'info'
  | 'infoBg'
  | 'infoLine'
  | 'radius1'
  | 'radius2'
  | 'radius3'
  | 'radius4'
  | 'shadow1'
  | 'shadow2'
  | 'shadowPop'
  | 'shadowHover'
  | 'shadowLifted'
  | 'ringFocus'
  | 'ringActive'
  | 'ringOk'
  | 'ringWarn'
  | 'ringErr'
  | 'ringInfo'
  | 'chromeBg'
  | 'chromeElev'
  | 'chromeSunken'
  | 'chromeHover'
  | 'chromeLine'
  | 'chromeLineStrong'
  | 'chromeInk1'
  | 'chromeInk2'
  | 'chromeInk3'
  | 'chromeInk4'
  | 'chromeActiveBg'
  | 'chromeActiveInk'
  | 'chromeActiveLine'
  | 'chromeControlRadius'
  | 'chromePopoverRadius'
  | 'brandMarkBg'
  | 'brandMarkInk'
  | 'ambientHero'
  | 'ambientCool'
  | 'ambientWarm'
  | 'layoutMenuBg'
  | 'layoutMenuPadding'
  | 'layoutMenuItemRadius'
  | 'layoutMenuItemActiveBg'
  | 'layoutMenuItemActiveColor'
  | 'layoutMenuItemActiveLine'
  | 'layoutMenuItemHoverBg'
  | 'layoutMenuSearchBg'
  | 'layoutMenuSearchBorder',
  string
>

const createThemeCssVars = (palette: ThemeCssVarPalette): ThemeStyleCssVars => ({
  '--primary-color': palette.primary,
  '--primary-color-1': palette.primarySoft,
  '--primary-color-2': palette.primarySoftAlt,
  '--primary-color-active': palette.primaryActive,
  '--jet-theme-primary-1': palette.primary1,
  '--jet-theme-primary-2': 'var(--primary-color-2)',
  '--jet-theme-primary-3': palette.primary3,
  '--jet-theme-primary-4': palette.primary4,
  '--jet-theme-primary-5': palette.primary5,
  '--brand-50': palette.brand50,
  '--brand-100': palette.brand100,
  '--brand-200': palette.brand200,
  '--brand-300': palette.brand300,
  '--brand-400': palette.brand400,
  '--brand-500': palette.brand500,
  '--brand-600': palette.brand600,
  '--brand-700': palette.brand700,
  '--brand-800': palette.brand800,
  '--brand-900': palette.brand900,
  '--jet-theme-primary': 'var(--primary-color)',
  '--jet-theme-primary-hover': palette.primaryHover,
  '--jet-theme-primary-active': 'var(--primary-color-active)',
  '--jet-theme-primary-soft': 'var(--primary-color-1)',
  '--accent-cyan': palette.accentCyan,
  '--accent-blue': palette.accentBlue,
  '--accent-pink': palette.accentPink,
  '--accent-magenta': palette.accentMagenta,
  '--macaron-orange-bg': palette.macaronOrangeBg,
  '--macaron-orange-text': palette.macaronOrangeText,
  '--macaron-orange-avatar': palette.macaronOrangeAvatar,
  '--macaron-blue-bg': palette.macaronBlueBg,
  '--macaron-blue-text': palette.macaronBlueText,
  '--macaron-blue-avatar': palette.macaronBlueAvatar,
  '--macaron-green-bg': palette.macaronGreenBg,
  '--macaron-green-text': palette.macaronGreenText,
  '--macaron-green-avatar': palette.macaronGreenAvatar,
  '--macaron-purple-bg': palette.macaronPurpleBg,
  '--macaron-purple-text': palette.macaronPurpleText,
  '--macaron-purple-avatar': palette.macaronPurpleAvatar,
  '--macaron-pink-bg': palette.macaronPinkBg,
  '--macaron-pink-text': palette.macaronPinkText,
  '--macaron-pink-avatar': palette.macaronPinkAvatar,
  '--macaron-yellow-bg': palette.macaronYellowBg,
  '--macaron-yellow-text': palette.macaronYellowText,
  '--macaron-yellow-avatar': palette.macaronYellowAvatar,
  '--canvas': palette.canvas,
  '--bg': palette.bg,
  '--bg-elev': palette.bgElev,
  '--bg-sunken': palette.bgSunken,
  '--bg-hover': palette.bgHover,
  '--bg-2': palette.bg2,
  '--line': palette.line,
  '--line-2': palette.line2,
  '--line-strong': palette.lineStrong,
  '--text-color': palette.text,
  '--text-color-secondary': palette.textSecondary,
  '--text-color-disabled': palette.textDisabled,
  '--jet-theme-text-title': 'var(--text-color)',
  '--jet-theme-text': 'var(--text-color)',
  '--jet-theme-text-secondary': 'var(--text-color-secondary)',
  '--jet-theme-text-description': 'var(--text-color-secondary)',
  '--jet-theme-text-disabled': 'var(--text-color-disabled)',
  '--ink-1': 'var(--text-color)',
  '--ink-2': 'var(--text-color-secondary)',
  '--ink-3': 'var(--text-color-disabled)',
  '--ink-4': 'var(--text-color-disabled)',
  '--ink-5': palette.ink5,
  '--accent': 'var(--primary-color)',
  '--accent-ink': palette.accentInk,
  '--accent-soft': 'var(--primary-color-1)',
  '--danger': palette.danger,
  '--danger-bg': palette.dangerBg,
  '--warning': palette.warning,
  '--warning-bg': palette.warningBg,
  '--success': palette.success,
  '--success-bg': palette.successBg,
  '--ok': palette.success,
  '--ok-bg': palette.successBg,
  '--ok-line': palette.okLine,
  '--warn': palette.warning,
  '--warn-bg': palette.warningBg,
  '--warn-line': palette.warnLine,
  '--err': palette.danger,
  '--err-bg': palette.dangerBg,
  '--err-line': palette.errLine,
  '--info': palette.info,
  '--info-bg': palette.infoBg,
  '--info-line': palette.infoLine,
  '--font-sans': 'var(--jet-theme-font-family)',
  '--font-cjk': 'var(--jet-theme-font-family)',
  '--font-mono': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  '--lh-tight': '1.2',
  '--lh-snug': '1.3',
  '--lh-normal': '1.55',
  '--lh-relaxed': '1.65',
  '--lh-loose': '1.8',
  '--fs-12': '0.75rem',
  '--fs-13': '0.875rem',
  '--fs-14': '0.875rem',
  '--fs-15': '0.9375rem',
  '--fs-16': '1rem',
  '--fs-17': '1.0625rem',
  '--fs-18': '1.125rem',
  '--fs-19': '1.1875rem',
  '--fs-20': '1.25rem',
  '--fs-21': '1.3125rem',
  '--fs-22': '1.375rem',
  '--fs-24': '1.5rem',
  '--fs-25': '1.5625rem',
  '--fs-26': '1.625rem',
  '--fs-28': '1.75rem',
  '--fs-30': '1.875rem',
  '--fs-32': '2rem',
  '--fs-34': '2.125rem',
  '--fs-36': '2.25rem',
  '--fs-38': '2.375rem',
  '--fs-40': '2.5rem',
  '--fs-42': '2.625rem',
  '--fs-44': '2.75rem',
  '--fs-46': '2.875rem',
  '--fs-48': '3rem',
  '--fs-54': '3.375rem',
  '--fs-56': '3.5rem',
  '--fs-60': '3.75rem',
  '--fs-64': '4rem',
  '--fs-90': '5.625rem',
  '--fs-100': '6.25rem',
  '--fs-tiny': 'var(--fs-12)',
  '--fs-pill': 'var(--fs-12)',
  '--fs-meta': 'var(--fs-12)',
  '--fs-caption': 'var(--fs-12)',
  '--fs-sm': 'var(--fs-13)',
  '--fs-body': 'var(--fs-14)',
  '--fs-label': 'var(--fs-12)',
  '--fs-title-4': 'var(--fs-16)',
  '--fs-title': 'var(--fs-18)',
  '--fs-h4': 'var(--fs-16)',
  '--fs-h3': 'var(--fs-18)',
  '--fs-h2': 'var(--fs-22)',
  '--fs-h1': 'var(--fs-24)',
  '--fs-display': 'var(--fs-24)',
  '--space-0': '0.25rem',
  '--space-1': '0.25rem',
  '--space-2': '0.5rem',
  '--space-3': '0.75rem',
  '--space-4': '1rem',
  '--space-5': '1.25rem',
  '--space-6': '1.5rem',
  '--space-7': '1.75rem',
  '--space-8': '2rem',
  '--space-9': '2.25rem',
  '--space-10': '2.5rem',
  '--space-11': '2.75rem',
  '--space-12': '3rem',
  '--space-13': '3.25rem',
  '--space-card': '1.5rem',
  '--space-card-lg': '2rem',
  '--space-section': '4rem',
  '--space-page': '6rem',
  '--space-gutter': 'clamp(1.25rem, 2.2vw, 3rem)',
  '--gap-card': '1.5rem',
  '--gap-section': '1.5rem',
  '--gap-rail': '1.5rem',
  '--padding-page-x': '2rem',
  '--padding-card': '1.5rem',
  '--padding-card-lg': '2rem',
  '--r-1': palette.radius1,
  '--r-2': palette.radius2,
  '--r-3': palette.radius3,
  '--r-4': palette.radius4,
  '--shadow-1': palette.shadow1,
  '--shadow-2': palette.shadow2,
  '--shadow-pop': palette.shadowPop,
  '--shadow-hover': palette.shadowHover,
  '--shadow-lifted': palette.shadowLifted,
  '--ring-focus': palette.ringFocus,
  '--ring-active': palette.ringActive,
  '--ring-ok': palette.ringOk,
  '--ring-warn': palette.ringWarn,
  '--ring-err': palette.ringErr,
  '--ring-info': palette.ringInfo,
  '--chrome-bg': palette.chromeBg,
  '--chrome-elev': palette.chromeElev,
  '--chrome-sunken': palette.chromeSunken,
  '--chrome-hover': palette.chromeHover,
  '--chrome-line': palette.chromeLine,
  '--chrome-line-strong': palette.chromeLineStrong,
  '--chrome-ink-1': palette.chromeInk1,
  '--chrome-ink-2': palette.chromeInk2,
  '--chrome-ink-3': palette.chromeInk3,
  '--chrome-ink-4': palette.chromeInk4,
  '--chrome-active-bg': palette.chromeActiveBg,
  '--chrome-active-ink': palette.chromeActiveInk,
  '--chrome-active-line': palette.chromeActiveLine,
  '--chrome-nav-font-size': '0.875rem',
  '--chrome-nav-font-weight': '400',
  '--chrome-active-font-weight': '600',
  '--chrome-brand-font-weight': '600',
  '--chrome-label-font-weight': '600',
  '--chrome-control-radius': palette.chromeControlRadius,
  '--chrome-popover-radius': palette.chromePopoverRadius,
  '--brand-mark-bg': palette.brandMarkBg,
  '--brand-mark-ink': palette.brandMarkInk,
  '--ambient-hero': palette.ambientHero,
  '--ambient-cool': palette.ambientCool,
  '--ambient-warm': palette.ambientWarm,
  '--code-dark-bg': '#0F172A',
  '--code-dark-fg-1': '#E2E8F0',
  '--code-dark-fg-2': '#CBD5E1',
  '--code-dark-fg-3': '#94A3B8',
  '--code-dark-line': 'rgb(255 255 255 / 0.06)',
  '--code-dark-hover': 'rgb(255 255 255 / 0.08)',
  '--topbar-h': '3rem',
  '--sidebar-w': '14rem',
  '--row-h': '2.25rem',
  '--pad-y': '0.5rem',
  '--layout-menu-bg': palette.layoutMenuBg,
  '--layout-menu-padding': palette.layoutMenuPadding,
  '--layout-menu-item-height': '2rem',
  '--layout-menu-item-radius': palette.layoutMenuItemRadius,
  '--layout-menu-item-active-bg': palette.layoutMenuItemActiveBg,
  '--layout-menu-item-active-color': palette.layoutMenuItemActiveColor,
  '--layout-menu-item-active-line': palette.layoutMenuItemActiveLine,
  '--layout-menu-item-hover-bg': palette.layoutMenuItemHoverBg,
  '--layout-menu-search-bg': palette.layoutMenuSearchBg,
  '--layout-menu-search-border': palette.layoutMenuSearchBorder
})

const sharedLayout = {
  menuVariant: 'compact-search',
  showMenuSearch: false,
  siderWidth: 224
} satisfies ThemeStyleToken['layout']

const sharedLayoutCssVars = {
  '--sidebar-w': '14rem',
  '--layout-menu-padding': '0.5rem 0.5rem',
  '--layout-menu-item-height': '2rem',
  '--layout-menu-item-radius': '6px'
} satisfies ThemeStyleCssVars

export const styleTokens = {
  'light': {
    label: '白色',
    colorPrimary: lightPrimaryColor,
    colorInfo: '#1677FF',
    colorSuccess: '#52C41A',
    colorWarning: '#FAAD14',
    colorError: '#FF4D4F',
    colorBgBase: '#FFFFFF',
    colorBgLayout: '#F5F5F5',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#000000',
    colorText: '#1A1A1A',
    colorTextSecondary: '#6B7280',
    colorBorder: '#D9D9D9',
    colorBorderSecondary: '#F0F0F0',
    borderRadius: Number(theme.borderRadius) || 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    boxShadow: '0 0.375rem 1rem 0 rgba(0, 0, 0, 0.08)',
    boxShadowSecondary: '0 0.125rem 0.5rem rgba(0, 0, 0, 0.06)',
    fontFamily: 'AliRegular, sans-serif',
    layout: sharedLayout,
    cssVars: {
      ...createThemeCssVars({
      primary: lightPrimaryColor,
      primarySoft: '#E6F4FF',
      primarySoftAlt: '#BAE0FF',
      primaryActive: '#0958D9',
      primary1: '#E6F4FF',
      primary2: '#BAE0FF',
      primary3: '#91CAFF',
      primary4: '#69B1FF',
      primary5: '#4096FF',
      brand50: '#E6F4FF',
      brand100: '#BAE0FF',
      brand200: '#91CAFF',
      brand300: '#69B1FF',
      brand400: '#4096FF',
      brand500: lightPrimaryColor,
      brand600: '#0958D9',
      brand700: '#003EB3',
      brand800: '#002C8C',
      brand900: '#001D66',
      primaryHover: '#4096FF',
      accentCyan: '#5CDBD3',
      accentBlue: '#4096FF',
      accentPink: '#FF85C0',
      accentMagenta: '#EB2F96',
      macaronOrangeBg: '#FFF7E6',
      macaronOrangeText: '#D46B08',
      macaronOrangeAvatar: '#FFD591',
      macaronBlueBg: '#E6F4FF',
      macaronBlueText: '#0958D9',
      macaronBlueAvatar: '#91CAFF',
      macaronGreenBg: '#F6FFED',
      macaronGreenText: '#389E0D',
      macaronGreenAvatar: '#B7EB8F',
      macaronPurpleBg: '#F9F0FF',
      macaronPurpleText: '#722ED1',
      macaronPurpleAvatar: '#D3ADF7',
      macaronPinkBg: '#FFF0F6',
      macaronPinkText: '#C41D7F',
      macaronPinkAvatar: '#FFADD2',
      macaronYellowBg: '#FFFBE6',
      macaronYellowText: '#D48806',
      macaronYellowAvatar: '#FFE58F',
      canvas: '#F5F5F5',
      bg: '#FFFFFF',
      bgElev: '#FFFFFF',
      bgSunken: '#F5F5F5',
      bgHover: '#F0F0F0',
      bg2: '#FAFAFA',
      line: '#F0F0F0',
      line2: '#F5F5F5',
      lineStrong: '#D9D9D9',
      text: '#1A1A1A',
      textSecondary: '#6B7280',
      textDisabled: '#9CA3AF',
      ink5: '#D1D5DB',
      accentInk: '#FFFFFF',
      danger: '#FF4D4F',
      dangerBg: '#FFF2F0',
      warning: '#FAAD14',
      warningBg: '#FFFBE6',
      success: '#52C41A',
      successBg: '#F6FFED',
      okLine: '#B7EB8F',
      warnLine: '#FFE58F',
      errLine: '#FFCCC7',
      info: '#1677FF',
      infoBg: '#E6F4FF',
      infoLine: '#BAE0FF',
      radius1: '0.25rem',
      radius2: '0.375rem',
      radius3: '0.5rem',
      radius4: '999px',
      shadow1: '0 1px 0 rgba(0, 0, 0, 0.03)',
      shadow2: '0 0.125rem 0.5rem rgba(0, 0, 0, 0.06)',
      shadowPop: '0 0.375rem 1rem rgba(0, 0, 0, 0.08)',
      shadowHover: '0 0.125rem 0.5rem rgba(0, 0, 0, 0.06)',
      shadowLifted: '0 0.375rem 1.25rem rgba(0, 0, 0, 0.06)',
      ringFocus: '0 0 0 0.1875rem #E6F4FF',
      ringActive: '0 0 0 0.125rem #E6F4FF',
      ringOk: '0 0 0 0.1875rem #F6FFED',
      ringWarn: '0 0 0 0.1875rem #FFFBE6',
      ringErr: '0 0 0 0.1875rem #FFF2F0',
      ringInfo: '0 0 0 0.1875rem #E6F4FF',
      chromeBg: '#FFFFFF',
      chromeElev: '#FFFFFF',
      chromeSunken: '#F5F5F5',
      chromeHover: '#F0F0F0',
      chromeLine: '#F0F0F0',
      chromeLineStrong: '#D9D9D9',
      chromeInk1: '#1A1A1A',
      chromeInk2: '#6B7280',
      chromeInk3: '#9CA3AF',
      chromeInk4: '#9CA3AF',
      chromeActiveBg: 'transparent',
      chromeActiveInk: lightPrimaryColor,
      chromeActiveLine: lightPrimaryColor,
      chromeControlRadius: '6px',
      chromePopoverRadius: '8px',
      brandMarkBg: '#1A1A1A',
      brandMarkInk: '#FFFFFF',
      ambientHero: 'linear-gradient(135deg, #E6F4FF, #F9F0FF, #FFF0F6)',
      ambientCool: 'linear-gradient(135deg, #E6F4FF, #F0F5FF)',
      ambientWarm: 'linear-gradient(135deg, #F9F0FF, #FFF0F6)',
      layoutMenuBg: '#FFFFFF',
      layoutMenuPadding: '0.5rem 0',
      layoutMenuItemRadius: '0',
      layoutMenuItemActiveBg: 'var(--jet-theme-primary-soft)',
      layoutMenuItemActiveColor: lightPrimaryColor,
      layoutMenuItemActiveLine: lightPrimaryColor,
      layoutMenuItemHoverBg: '#F5F5F5',
      layoutMenuSearchBg: '#FFFFFF',
      layoutMenuSearchBorder: '#F0F0F0'
      }),
      ...sharedLayoutCssVars
    }
  },
  dark: {
    label: '黑色',
    colorPrimary: '#69B1FF',
    colorInfo: '#69B1FF',
    colorSuccess: '#49AA19',
    colorWarning: '#D89614',
    colorError: '#DC4446',
    colorBgBase: '#141414',
    colorBgLayout: '#000000',
    colorBgContainer: '#1F1F1F',
    colorBgElevated: '#262626',
    colorTextBase: '#FFFFFF',
    colorText: 'rgba(255, 255, 255, 0.88)',
    colorTextSecondary: 'rgba(255, 255, 255, 0.65)',
    colorBorder: '#424242',
    colorBorderSecondary: '#303030',
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    boxShadow: '0 0.5rem 1.5rem rgba(0, 0, 0, 0.45)',
    boxShadowSecondary: '0 0.125rem 0.5rem rgba(0, 0, 0, 0.35)',
    fontFamily: 'AliRegular, sans-serif',
    layout: sharedLayout,
    cssVars: {
      ...createThemeCssVars({
      primary: '#69B1FF',
      primarySoft: '#111D2C',
      primarySoftAlt: '#15325B',
      primaryActive: '#4096FF',
      primary1: '#111D2C',
      primary2: '#15325B',
      primary3: '#15417E',
      primary4: '#1554AD',
      primary5: '#1668DC',
      brand50: '#111D2C',
      brand100: '#15325B',
      brand200: '#15417E',
      brand300: '#1554AD',
      brand400: '#1668DC',
      brand500: '#69B1FF',
      brand600: '#4096FF',
      brand700: '#1677FF',
      brand800: '#0958D9',
      brand900: '#003EB3',
      primaryHover: '#91CAFF',
      accentCyan: '#36CFC9',
      accentBlue: '#69B1FF',
      accentPink: '#FF85C0',
      accentMagenta: '#EB2F96',
      macaronOrangeBg: '#2B1D11',
      macaronOrangeText: '#FFD591',
      macaronOrangeAvatar: '#D46B08',
      macaronBlueBg: '#111D2C',
      macaronBlueText: '#91CAFF',
      macaronBlueAvatar: '#1668DC',
      macaronGreenBg: '#162312',
      macaronGreenText: '#95DE64',
      macaronGreenAvatar: '#389E0D',
      macaronPurpleBg: '#1F1A2E',
      macaronPurpleText: '#D3ADF7',
      macaronPurpleAvatar: '#722ED1',
      macaronPinkBg: '#2A1325',
      macaronPinkText: '#FFADD2',
      macaronPinkAvatar: '#C41D7F',
      macaronYellowBg: '#2B2611',
      macaronYellowText: '#FFE58F',
      macaronYellowAvatar: '#D48806',
      canvas: '#000000',
      bg: '#1F1F1F',
      bgElev: '#262626',
      bgSunken: '#141414',
      bgHover: '#2A2A2A',
      bg2: '#141414',
      line: '#303030',
      line2: '#262626',
      lineStrong: '#424242',
      text: 'rgba(255, 255, 255, 0.88)',
      textSecondary: 'rgba(255, 255, 255, 0.65)',
      textDisabled: 'rgba(255, 255, 255, 0.35)',
      ink5: '#595959',
      accentInk: '#141414',
      danger: '#DC4446',
      dangerBg: '#2A1215',
      warning: '#D89614',
      warningBg: '#2B2111',
      success: '#49AA19',
      successBg: '#162312',
      okLine: '#274916',
      warnLine: '#594214',
      errLine: '#58181C',
      info: '#69B1FF',
      infoBg: '#111D2C',
      infoLine: '#15325B',
      radius1: '0.25rem',
      radius2: '0.375rem',
      radius3: '0.5rem',
      radius4: '999px',
      shadow1: '0 1px 0 rgba(0, 0, 0, 0.24)',
      shadow2: '0 0.125rem 0.5rem rgba(0, 0, 0, 0.35)',
      shadowPop: '0 0.5rem 1.5rem rgba(0, 0, 0, 0.45)',
      shadowHover: '0 0.25rem 0.75rem rgba(0, 0, 0, 0.4)',
      shadowLifted: '0 0.5rem 1.5rem rgba(0, 0, 0, 0.45)',
      ringFocus: '0 0 0 0.1875rem #111D2C',
      ringActive: '0 0 0 0.125rem #15325B',
      ringOk: '0 0 0 0.1875rem #162312',
      ringWarn: '0 0 0 0.1875rem #2B2111',
      ringErr: '0 0 0 0.1875rem #2A1215',
      ringInfo: '0 0 0 0.1875rem #111D2C',
      chromeBg: '#1F1F1F',
      chromeElev: '#262626',
      chromeSunken: '#141414',
      chromeHover: '#2A2A2A',
      chromeLine: '#303030',
      chromeLineStrong: '#424242',
      chromeInk1: 'rgba(255, 255, 255, 0.88)',
      chromeInk2: 'rgba(255, 255, 255, 0.65)',
      chromeInk3: 'rgba(255, 255, 255, 0.45)',
      chromeInk4: 'rgba(255, 255, 255, 0.35)',
      chromeActiveBg: 'transparent',
      chromeActiveInk: '#69B1FF',
      chromeActiveLine: '#69B1FF',
      chromeControlRadius: '6px',
      chromePopoverRadius: '8px',
      brandMarkBg: 'rgba(255, 255, 255, 0.88)',
      brandMarkInk: '#141414',
      ambientHero: 'linear-gradient(135deg, #111D2C, #1F1A2E, #2A1325)',
      ambientCool: 'linear-gradient(135deg, #111D2C, #141414)',
      ambientWarm: 'linear-gradient(135deg, #1F1A2E, #2A1325)',
      layoutMenuBg: '#1F1F1F',
      layoutMenuPadding: '0.5rem 0',
      layoutMenuItemRadius: '0',
      layoutMenuItemActiveBg: 'transparent',
      layoutMenuItemActiveColor: '#69B1FF',
      layoutMenuItemActiveLine: '#69B1FF',
      layoutMenuItemHoverBg: '#2A2A2A',
      layoutMenuSearchBg: '#1F1F1F',
      layoutMenuSearchBorder: '#303030'
      }),
      ...sharedLayoutCssVars
    }
  },
  // ai: {
  //   label: 'AI风格',
  //   colorPrimary: '#2C4A7C',
  //   colorInfo: '#3E5A78',
  //   colorSuccess: '#4A6B48',
  //   colorWarning: '#8A6B2A',
  //   colorError: '#8A3A3A',
  //   colorBgBase: '#FFFFFF',
  //   colorBgLayout: '#F6F7F9',
  //   colorBgContainer: '#FFFFFF',
  //   colorBgElevated: '#FFFFFF',
  //   colorTextBase: '#1D1F24',
  //   colorText: '#1A1A1A',
  //   colorTextSecondary: '#6B7280',
  //   colorBorder: '#E6E7EB',
  //   colorBorderSecondary: '#D2D4DA',
  //   borderRadius: 6,
  //   borderRadiusLG: 8,
  //   borderRadiusSM: 4,
  //   boxShadow: '0 0.25rem 0.75rem rgba(0, 0, 0, 0.06), 0 0 0 1px rgba(0, 0, 0, 0.04)',
  //   boxShadowSecondary: '0 1px 0.125rem rgba(0, 0, 0, 0.04), 0 0 0 1px rgba(0, 0, 0, 0.02)',
  //   fontFamily: 'var(--font-sans)',
  //     fontSize: 'var(--fs-14)',
  //   layout: {
  //     menuVariant: 'compact-search',
  //     showMenuSearch: false,
  //     siderWidth: 224
  //   },
  //   cssVars: {
  //     '--canvas': '#F6F7F9',
  //     '--bg': '#FFFFFF',
  //     '--bg-elev': '#FFFFFF',
  //     '--bg-sunken': '#F1F2F4',
  //     '--bg-hover': '#EAECEF',
  //     '--line': '#E6E7EB',
  //     '--line-strong': '#D2D4DA',
  //     '--jet-theme-text-disabled': '#9CA3AF',
  //     '--ink-1': '#1A1A1A',
  //     '--ink-2': '#6B7280',
  //     '--ink-3': '#9CA3AF',
  //     '--ink-4': '#9CA3AF',
  //     '--accent': 'var(--jet-theme-primary)',
  //     '--accent-ink': '#FFFFFF',
  //     '--accent-soft': 'var(--jet-theme-primary-soft)',
  //     '--jet-theme-stroke-width': '1px',
  //     '--chrome-bg': 'var(--bg)',
  //     '--chrome-elev': 'var(--bg-elev)',
  //     '--chrome-sunken': 'var(--bg-sunken)',
  //     '--chrome-hover': 'var(--bg-hover)',
  //     '--chrome-line': 'var(--line)',
  //     '--chrome-line-strong': 'var(--line-strong)',
  //     '--chrome-ink-1': 'var(--ink-1)',
  //     '--chrome-ink-2': 'var(--ink-2)',
  //     '--chrome-ink-3': 'var(--ink-3)',
  //     '--chrome-ink-4': 'var(--ink-4)',
  //     '--chrome-active-bg': 'transparent',
  //     '--chrome-active-ink': 'var(--chrome-ink-1)',
  //     '--chrome-active-line': 'var(--accent)',
  //     '--brand-mark-bg': 'var(--ink-1)',
  //     '--brand-mark-ink': 'var(--bg-elev)',
  //     '--chrome-nav-font-size': 'var(--fs-14)',
  //     '--chrome-nav-font-weight': '400',
  //     '--chrome-active-font-weight': '500',
  //     '--chrome-brand-font-weight': '600',
  //     '--chrome-label-font-weight': '600',
  //     '--chrome-control-radius': 'var(--r-2)',
  //     '--chrome-popover-radius': 'var(--r-3)',
  //     '--ok': '#4A6B48',
  //     '--ok-bg': '#EEF0E9',
  //     '--ok-line': '#D9E0D3',
  //     '--warn': '#8A6B2A',
  //     '--warn-bg': '#F4EDE0',
  //     '--warn-line': '#E6D9BD',
  //     '--err': '#8A3A3A',
  //     '--err-bg': '#F1E6E3',
  //     '--err-line': '#E4D0CC',
  //     '--info': '#3E5A78',
  //     '--info-bg': '#E9EDF2',
  //     '--info-line': '#D8E0E9',
  //     '--font-sans': 'AliRegular',
  //     '--font-cjk': 'AliRegular',
  //     '--font-mono': 'AliRegular',
  //     '--lh-tight': '1.15',
  //     '--lh-snug': '1.35',
  //     '--lh-normal': '1.5',
  //     '--lh-relaxed': '1.65',
  //     '--lh-loose': '1.8',
  //     '--fs-12': '0.75rem',
  //     '--fs-13': '0.8125rem',
  //     '--fs-14': '0.875rem',
  //     '--fs-15': '0.9375rem',
  //     '--fs-16': '1rem',
  //     '--fs-17': '1.0625rem',
  //     '--fs-18': '1.125rem',
  //     '--fs-19': '1.1875rem',
  //     '--fs-20': '1.25rem',
  //     '--fs-21': '1.3125rem',
  //     '--fs-22': '1.375rem',
  //     '--fs-24': '1.5rem',
  //     '--fs-25': '1.5625rem',
  //     '--fs-26': '1.625rem',
  //     '--fs-28': '1.75rem',
  //     '--fs-30': '1.875rem',
  //     '--fs-32': '2rem',
  //     '--fs-34': '2.125rem',
  //     '--fs-36': '2.25rem',
  //     '--fs-38': '2.375rem',
  //     '--fs-40': '2.5rem',
  //     '--fs-42': '2.625rem',
  //     '--fs-44': '2.75rem',
  //     '--fs-46': '2.875rem',
  //     '--fs-48': '3rem',
  //     '--fs-54': '3.375rem',
  //     '--fs-56': '3.5rem',
  //     '--fs-60': '3.75rem',
  //     '--fs-64': '4rem',
  //     '--fs-90': '5.625rem',
  //     '--fs-100': '6.25rem',
  //     '--fs-tiny': 'var(--fs-12)',
  //     '--fs-pill': 'var(--fs-12)',
  //     '--fs-meta': 'var(--fs-12)',
  //     '--fs-caption': 'var(--fs-12)',
  //     '--fs-sm': 'var(--fs-13)',
  //     '--fs-body': 'var(--fs-14)',
  //     '--fs-label': 'var(--fs-12)',
  //     '--fs-title-4': 'var(--fs-16)',
  //     '--fs-title': 'var(--fs-18)',
  //     '--fs-h4': 'var(--fs-16)',
  //     '--fs-h3': 'var(--fs-18)',
  //     '--fs-h2': 'var(--fs-22)',
  //     '--fs-h1': 'var(--fs-24)',
  //     '--fs-display': 'var(--fs-24)',
  //     '--space-1': '0.25rem',
  //     '--space-2': '0.5rem',
  //     '--space-3': '0.75rem',
  //     '--space-4': '1rem',
  //     '--space-5': '1.25rem',
  //     '--space-6': '1.5rem',
  //     '--space-7': '1.75rem',
  //     '--space-8': '2rem',
  //     '--space-9': '2.25rem',
  //     '--space-10': '2.5rem',
  //     '--space-11': '2.75rem',
  //     '--space-12': '3rem',
  //     '--space-13': '3.25rem',
  //     '--space-section': '4rem',
  //     '--space-page': '6rem',
  //     '--space-gutter': 'clamp(1.25rem, 2.2vw, 3rem)',
  //     '--r-1': '0.25rem',
  //     '--r-2': '0.375rem',
  //     '--r-3': '0.5rem',
  //     '--r-4': '0.625rem',
  //     '--shadow-1': '0 1px 0 rgba(0, 0, 0, 0.03)',
  //     '--shadow-2': '0 1px 0.125rem rgba(0, 0, 0, 0.04), 0 0 0 1px rgba(0, 0, 0, 0.02)',
  //     '--shadow-pop': '0 0.25rem 0.75rem rgba(0, 0, 0, 0.06), 0 0 0 1px rgba(0, 0, 0, 0.04)',
  //     '--shadow-hover': '0 0.125rem 0.5rem rgba(0, 0, 0, 0.06)',
  //     '--shadow-lifted': '0 0.375rem 1.25rem rgba(0, 0, 0, 0.06)',
  //     '--ring-focus': '0 0 0 0.1875rem var(--accent-soft)',
  //     '--ring-active': '0 0 0 0.125rem var(--accent-soft)',
  //     '--ring-ok': '0 0 0 0.1875rem var(--ok-bg)',
  //     '--ring-warn': '0 0 0 0.1875rem var(--warn-bg)',
  //     '--ring-err': '0 0 0 0.1875rem var(--err-bg)',
  //     '--ring-info': '0 0 0 0.1875rem var(--info-bg)',
  //     '--shadow-sticky-top': '0 -0.25rem 0.75rem rgba(0, 0, 0, 0.04)',
  //     '--shadow-fab': '0 0.375rem 1rem rgba(0, 0, 0, 0.12), 0 0.125rem 0.375rem rgba(0, 0, 0, 0.08)',
  //     '--z-dev-tools': '9999',
  //     '--ind-rail': 'var(--ink-1)',
  //     '--ind-rail-banner': 'var(--bg-sunken)',
  //     '--ind-rail-mark': 'var(--accent-soft)',
  //     '--ind-fuel': 'var(--ink-1)',
  //     '--ind-fuel-banner': 'var(--bg-sunken)',
  //     '--ind-fuel-mark': 'var(--accent-soft)',
  //     '--ind-park': 'var(--ink-1)',
  //     '--ind-park-banner': 'var(--bg-sunken)',
  //     '--ind-park-mark': 'var(--accent-soft)',
  //     '--ind-care': 'var(--ink-1)',
  //     '--ind-care-banner': 'var(--bg-sunken)',
  //     '--ind-care-mark': 'var(--accent-soft)',
  //     '--ind-industry': 'var(--ink-1)',
  //     '--ind-industry-banner': 'var(--bg-sunken)',
  //     '--ind-industry-mark': 'var(--accent-soft)',
  //     '--ind-safety': 'var(--ink-1)',
  //     '--ind-safety-banner': 'var(--bg-sunken)',
  //     '--ind-safety-mark': 'var(--accent-soft)',
  //     '--ind-energy': 'var(--ink-1)',
  //     '--ind-energy-banner': 'var(--bg-sunken)',
  //     '--ind-energy-mark': 'var(--accent-soft)',
  //     '--ind-general': 'var(--ink-2)',
  //     '--ind-general-banner': 'var(--bg-sunken)',
  //     '--ind-general-mark': 'var(--bg-sunken)',
  //     '--cp-scene': 'var(--ink-1)',
  //     '--cp-scene-bg': 'var(--accent-soft)',
  //     '--cp-protocol': 'var(--ink-1)',
  //     '--cp-protocol-bg': 'var(--accent-soft)',
  //     '--cp-skill': 'var(--ink-1)',
  //     '--cp-skill-bg': 'var(--accent-soft)',
  //     '--cp-screen': 'var(--ink-1)',
  //     '--cp-screen-bg': 'var(--accent-soft)',
  //     '--cp-kb': 'var(--ink-2)',
  //     '--cp-kb-bg': 'var(--bg-sunken)',
  //     '--cap-scene-pack': 'var(--ink-1)',
  //     '--cap-scene-pack-bg': 'var(--accent-soft)',
  //     '--cap-device': 'var(--ink-1)',
  //     '--cap-device-bg': 'var(--accent-soft)',
  //     '--cap-screen': 'var(--ink-1)',
  //     '--cap-screen-bg': 'var(--accent-soft)',
  //     '--cap-agent': 'var(--ink-1)',
  //     '--cap-agent-bg': 'var(--accent-soft)',
  //     '--cap-vision': 'var(--ink-1)',
  //     '--cap-vision-bg': 'var(--accent-soft)',
  //     '--cap-skill': 'var(--ink-1)',
  //     '--cap-skill-bg': 'var(--accent-soft)',
  //     '--ambient-hero': 'linear-gradient(135deg, #eef4ff, #f5f3ff, #fdf2f8)',
  //     '--ambient-cool': 'linear-gradient(135deg, #eef4ff, #f5f3ff)',
  //     '--ambient-warm': 'linear-gradient(135deg, #f5f3ff, #fdf2f8)',
  //     '--code-dark-bg': '#0F172A',
  //     '--code-dark-fg-1': '#E2E8F0',
  //     '--code-dark-fg-2': '#CBD5E1',
  //     '--code-dark-fg-3': '#94A3B8',
  //     '--code-dark-line': 'rgb(255 255 255 / 0.06)',
  //     '--code-dark-hover': 'rgb(255 255 255 / 0.08)',
  //     '--topbar-h': '3rem',
  //     '--sidebar-w': '14.75rem',
  //     '--row-h': '2.25rem',
  //     '--pad-y': '0.5rem',
  //     '--layout-menu-bg': '#FFFFFF',
  //     '--layout-menu-padding': '0.5rem 0.5rem',
  //     '--layout-menu-item-height': '2rem',
  //     '--layout-menu-item-radius': '0.375rem',
  //     '--layout-menu-item-active-bg': '#F1F2F4',
  //     '--layout-menu-item-active-color': 'var(--jet-theme-text)',
  //     '--layout-menu-item-active-line': 'var(--jet-theme-primary)',
  //     '--layout-menu-item-hover-bg': '#F6F7F9',
  //     '--layout-menu-search-bg': '#F6F7F9',
  //     '--layout-menu-search-border': '#E6E7EB'
  //   }
  // },
  ai: {
    label: 'AI',
    colorPrimary: '#6E4BFF',
    colorPrimaryHover: '#5D3AEF',
    colorPrimaryActive: '#4A2DCC',
    colorLink: '#6E4BFF',
    colorLinkHover: '#5D3AEF',
    colorLinkActive: '#4A2DCC',
    colorInfo: '#2A6FDB',
    colorSuccess: '#1F8A5B',
    colorWarning: '#DE9402',
    colorError: '#E0354B',
    colorBgBase: '#FFFFFF',
    colorBgLayout: '#FAFBFC',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#111418',
    colorText: '#111418',
    colorTextSecondary: '#3A3F47',
    colorBorder: '#EBEDF0',
    colorBorderSecondary: '#F4F5F7',
    borderRadius: 6,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    boxShadow: '0 0.25rem 1rem rgba(20, 22, 30, 0.06)',
    boxShadowSecondary: '0 1px 0.125rem rgba(20, 22, 30, 0.04)',
    fontFamily: 'AliRegular, sans-serif',
    layout: sharedLayout,
    cssVars: {
      '--primary-color': '#6E4BFF',
      '--primary-color-1': '#ECE7FF',
      '--primary-color-2': '#ECE7FF',
      '--primary-color-active': '#4A2DCC',
      '--jet-theme-primary-1': '#F6F4FF',
      '--jet-theme-primary-2': 'var(--primary-color-2)',
      '--jet-theme-primary-3': '#DDD4FF',
      '--jet-theme-primary-4': '#C0B0FF',
      '--jet-theme-primary-5': '#9C82FF',
      '--brand-50': '#F6F4FF',
      '--brand-100': '#ECE7FF',
      '--brand-200': '#DDD4FF',
      '--brand-300': '#C0B0FF',
      '--brand-400': '#9C82FF',
      '--brand-500': '#6E4BFF',
      '--brand-600': '#5D3AEF',
      '--brand-700': '#4A2DCC',
      '--brand-800': '#36219B',
      '--brand-900': '#211262',
      '--jet-theme-primary': 'var(--primary-color)',
      '--jet-theme-primary-hover': '#5D3AEF',
      '--jet-theme-primary-active': 'var(--primary-color-active)',
      '--jet-theme-primary-soft': 'var(--primary-color-1)',
      '--accent-cyan': '#A8EFFF',
      '--accent-blue': '#5BD2F0',
      '--accent-pink': '#FF8FCB',
      '--accent-magenta': '#E94B9B',
      '--macaron-orange-bg': '#FFF1E6',
      '--macaron-orange-text': '#C26410',
      '--macaron-orange-avatar': '#FFB988',
      '--macaron-blue-bg': '#E8EEFF',
      '--macaron-blue-text': '#2E4FB8',
      '--macaron-blue-avatar': '#9FB7FF',
      '--macaron-green-bg': '#E8F4EC',
      '--macaron-green-text': '#1E7A4F',
      '--macaron-green-avatar': '#86D3A8',
      '--macaron-purple-bg': '#EFE9FF',
      '--macaron-purple-text': '#5D3AEF',
      '--macaron-purple-avatar': '#C9B3FF',
      '--macaron-pink-bg': '#FFE6F0',
      '--macaron-pink-text': '#B82E6E',
      '--macaron-pink-avatar': '#FFB3D1',
      '--macaron-yellow-bg': '#FFF4D6',
      '--macaron-yellow-text': '#8A6410',
      '--macaron-yellow-avatar': '#FFD980',
      '--canvas': '#FAFBFC',
      '--bg': '#FFFFFF',
      '--bg-elev': '#FFFFFF',
      '--bg-sunken': '#F6F4FF',
      '--bg-hover': '#F4F5F7',
      '--bg-2': '#FAFBFC',
      '--line': '#EBEDF0',
      '--line-2': '#F4F5F7',
      '--line-strong': '#C5CAD1',
      '--text-color': '#111418',
      '--text-color-secondary': '#3A3F47',
      '--text-color-disabled': '#9AA1AB',
      '--jet-theme-text-title': 'var(--text-color)',
      '--jet-theme-text': 'var(--text-color)',
      '--jet-theme-text-secondary': 'var(--text-color-secondary)',
      '--jet-theme-text-description': 'var(--text-color-secondary)',
      '--jet-theme-text-disabled': 'var(--text-color-disabled)',
      '--ink-1': 'var(--text-color)',
      '--ink-2': 'var(--text-color-secondary)',
      '--ink-3': 'var(--text-color-disabled)',
      '--ink-4': 'var(--text-color-disabled)',
      '--ink-5': '#C5CAD1',
      '--accent': 'var(--primary-color)',
      '--accent-ink': '#FFFFFF',
      '--accent-soft': 'var(--primary-color-1)',
      '--danger': '#E0354B',
      '--danger-bg': '#FBE7EB',
      '--warning': '#DE9402',
      '--warning-bg': '#FBF2DD',
      '--success': '#1F8A5B',
      '--success-bg': '#E6F4EC',
      '--ok': '#1F8A5B',
      '--ok-bg': '#E6F4EC',
      '--ok-line': '#BFE5CF',
      '--warn': '#DE9402',
      '--warn-bg': '#FBF2DD',
      '--warn-line': '#EFD7A2',
      '--err': '#E0354B',
      '--err-bg': '#FBE7EB',
      '--err-line': '#F1B7C0',
      '--info': 'var(--primary-color)',
      '--info-bg': 'var(--primary-color-1)',
      '--info-line': '#C9D9FF',
      '--font-sans': 'var(--jet-theme-font-family)',
      '--font-cjk': 'var(--jet-theme-font-family)',
      '--font-mono': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
      '--lh-tight': '1.2',
      '--lh-snug': '1.3',
      '--lh-normal': '1.55',
      '--lh-relaxed': '1.65',
      '--lh-loose': '1.8',
        '--fs-12': '0.75rem',
        '--fs-13': '0.875rem',
        '--fs-14': '0.875rem',
      '--fs-15': '0.9375rem',
      '--fs-16': '1rem',
      '--fs-17': '1.0625rem',
      '--fs-18': '1.125rem',
      '--fs-19': '1.1875rem',
      '--fs-20': '1.25rem',
      '--fs-21': '1.3125rem',
      '--fs-22': '1.375rem',
      '--fs-24': '1.5rem',
      '--fs-25': '1.5625rem',
      '--fs-26': '1.625rem',
      '--fs-28': '1.75rem',
      '--fs-30': '1.875rem',
      '--fs-32': '2rem',
      '--fs-34': '2.125rem',
      '--fs-36': '2.25rem',
      '--fs-38': '2.375rem',
      '--fs-40': '2.5rem',
      '--fs-42': '2.625rem',
      '--fs-44': '2.75rem',
      '--fs-46': '2.875rem',
      '--fs-48': '3rem',
      '--fs-54': '3.375rem',
      '--fs-56': '3.5rem',
      '--fs-60': '3.75rem',
      '--fs-64': '4rem',
      '--fs-90': '5.625rem',
      '--fs-100': '6.25rem',
      '--fs-tiny': 'var(--fs-12)',
      '--fs-pill': 'var(--fs-12)',
      '--fs-meta': 'var(--fs-12)',
      '--fs-caption': 'var(--fs-12)',
      '--fs-sm': 'var(--fs-13)',
      '--fs-body': 'var(--fs-14)',
      '--fs-label': 'var(--fs-12)',
      '--fs-title-4': 'var(--fs-16)',
      '--fs-title': 'var(--fs-18)',
      '--fs-h4': 'var(--fs-16)',
      '--fs-h3': 'var(--fs-18)',
      '--fs-h2': 'var(--fs-22)',
      '--fs-h1': 'var(--fs-24)',
      '--fs-display': 'var(--fs-24)',
      '--space-0': '0.25rem',
      '--space-1': '0.25rem',
      '--space-2': '0.5rem',
      '--space-3': '0.75rem',
      '--space-4': '1rem',
      '--space-5': '1.25rem',
      '--space-6': '1.5rem',
      '--space-7': '1.75rem',
      '--space-8': '2rem',
      '--space-9': '2.25rem',
      '--space-10': '2.5rem',
      '--space-11': '2.75rem',
      '--space-12': '3rem',
      '--space-13': '3.25rem',
      '--space-card': '1.5rem',
      '--space-card-lg': '2rem',
      '--space-section': '4rem',
      '--space-page': '6rem',
      '--space-gutter': 'clamp(1.25rem, 2.2vw, 3rem)',
      '--gap-card': '1.5rem',
      '--gap-section': '1.5rem',
      '--gap-rail': '1.5rem',
      '--padding-page-x': '2rem',
      '--padding-card': '1.5rem',
      '--padding-card-lg': '2rem',
      '--r-1': '0.375rem',
      '--r-2': '0.5rem',
      '--r-3': '0.75rem',
      '--r-4': '999px',
      '--shadow-1': '0 1px 0.125rem rgba(20, 22, 30, 0.04)',
      '--shadow-2': '0 0.25rem 1rem rgba(20, 22, 30, 0.06)',
      '--shadow-pop': '0 0.25rem 1rem rgba(20, 22, 30, 0.06)',
      '--shadow-hover': '0 0.25rem 1rem rgba(20, 22, 30, 0.06)',
      '--shadow-lifted': '0 0.25rem 1rem rgba(20, 22, 30, 0.06)',
      '--ring-focus': '0 0 0 0.1875rem #ECE7FF',
      '--ring-active': '0 0 0 0.125rem #ECE7FF',
      '--ring-ok': '0 0 0 0.1875rem #E6F4EC',
      '--ring-warn': '0 0 0 0.1875rem #FBF2DD',
      '--ring-err': '0 0 0 0.1875rem #FBE7EB',
      '--ring-info': '0 0 0 0.1875rem #EEF3FF',
      '--chrome-bg': '#FFFFFF',
      '--chrome-elev': '#FFFFFF',
      '--chrome-sunken': '#F6F4FF',
      '--chrome-hover': '#F4F5F7',
      '--chrome-line': '#EBEDF0',
      '--chrome-line-strong': '#C5CAD1',
      '--chrome-ink-1': '#111418',
      '--chrome-ink-2': '#3A3F47',
      '--chrome-ink-3': '#6B727D',
      '--chrome-ink-4': '#9AA1AB',
      '--chrome-active-bg': '#ECE7FF',
      '--chrome-active-ink': '#6E4BFF',
      '--chrome-active-line': '#6E4BFF',
      '--chrome-nav-font-size': '0.875rem',
      '--chrome-nav-font-weight': '400',
      '--chrome-active-font-weight': '600',
      '--chrome-brand-font-weight': '600',
      '--chrome-label-font-weight': '600',
      '--chrome-control-radius': '6px',
      '--chrome-popover-radius': '12px',
      '--brand-mark-bg': '#111418',
      '--brand-mark-ink': '#FFFFFF',
      '--ambient-hero': 'linear-gradient(135deg, #F6F4FF, #ECE7FF)',
      '--ambient-cool': 'linear-gradient(135deg, #F6F4FF, #FAFBFC)',
      '--ambient-warm': 'linear-gradient(135deg, #FFFFFF, #F6F4FF)',
      '--code-dark-bg': '#0F172A',
      '--code-dark-fg-1': '#E2E8F0',
      '--code-dark-fg-2': '#CBD5E1',
      '--code-dark-fg-3': '#94A3B8',
      '--code-dark-line': 'rgb(255 255 255 / 0.06)',
      '--code-dark-hover': 'rgb(255 255 255 / 0.08)',
      '--topbar-h': '3rem',
      '--row-h': '2.25rem',
      '--pad-y': '0.5rem',
      '--layout-menu-bg': '#FFFFFF',
      '--layout-menu-item-active-bg': '#ECE7FF',
      '--layout-menu-item-active-color': '#6E4BFF',
      '--layout-menu-item-active-line': '#6E4BFF',
      '--layout-menu-item-hover-bg': '#F6F4FF',
      '--layout-menu-search-bg': '#FAFBFC',
      '--layout-menu-search-border': '#EBEDF0',
      ...sharedLayoutCssVars
    }
  }
} satisfies Record<string, ThemeStyleToken>
