import { DEFAULT_THEME_COLOR, normalizeThemeColor } from '@/utils/theme-color'
import theme from '@theme-config'
import { ThemeStyleToken } from '@/utils/theme-style'

export const styleTokens = {
  'light': {
    label: '白色',
    colorPrimary: normalizeThemeColor(theme.colorPrimary) || DEFAULT_THEME_COLOR,
    colorInfo: '#1677FF',
    colorSuccess: '#52C41A',
    colorWarning: '#FAAD14',
    colorError: '#FF4D4F',
    colorBgBase: '#FFFFFF',
    colorBgLayout: '#F5F5F5',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#000000',
    colorText: 'rgba(0, 0, 0, 0.88)',
    colorTextSecondary: 'rgba(0, 0, 0, 0.65)',
    colorBorder: '#D9D9D9',
    colorBorderSecondary: '#F0F0F0',
    borderRadius: Number(theme.borderRadius) || 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    boxShadow: '0 6px 16px 0 rgba(0, 0, 0, 0.08)',
    boxShadowSecondary: '0 2px 8px rgba(0, 0, 0, 0.06)'
  },
  dark: {
    label: '黑色',
    colorPrimary: '#69B1FF',
    colorInfo: '#69B1FF',
    colorSuccess: '#49AA19',
    colorWarning: '#D89614',
    colorError: '#DC4446',
    colorBgBase: '#141414',
    colorBgLayout: '#000000',
    colorBgContainer: '#1F1F1F',
    colorBgElevated: '#262626',
    colorTextBase: '#FFFFFF',
    colorText: 'rgba(255, 255, 255, 0.88)',
    colorTextSecondary: 'rgba(255, 255, 255, 0.65)',
    colorBorder: '#424242',
    colorBorderSecondary: '#303030',
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.45)',
    boxShadowSecondary: '0 2px 8px rgba(0, 0, 0, 0.35)'
  },
  mui: {
    label: 'MUI 风格',
    colorPrimary: '#1976D2',
    colorInfo: '#0288D1',
    colorSuccess: '#2E7D32',
    colorWarning: '#ED6C02',
    colorError: '#D32F2F',
    colorBgBase: '#FFFFFF',
    colorBgLayout: '#F4F6F8',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#1D1D1F',
    colorText: 'rgba(0, 0, 0, 0.87)',
    colorTextSecondary: 'rgba(0, 0, 0, 0.6)',
    colorBorder: 'rgba(0, 0, 0, 0.12)',
    colorBorderSecondary: 'rgba(0, 0, 0, 0.08)',
    borderRadius: 4,
    borderRadiusLG: 6,
    borderRadiusSM: 3,
    boxShadow: '0 3px 6px rgba(0, 0, 0, 0.16)',
    boxShadowSecondary: '0 1px 3px rgba(0, 0, 0, 0.12)',
    fontFamily: 'Roboto, AliRegular, sans-serif'
  },
  cartoon: {
    label: '卡通风格',
    colorPrimary: '#FF7A45',
    colorInfo: '#36CFC9',
    colorSuccess: '#73D13D',
    colorWarning: '#FFC53D',
    colorError: '#FF4D4F',
    colorBgBase: '#FFF7E6',
    colorBgLayout: '#FFF1D6',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#332018',
    colorText: '#332018',
    colorTextSecondary: '#7A4E2B',
    colorBorder: '#FFD591',
    colorBorderSecondary: '#FFE7BA',
    borderRadius: 14,
    borderRadiusLG: 18,
    borderRadiusSM: 10,
    boxShadow: '0 6px 0 rgba(122, 78, 43, 0.16)',
    boxShadowSecondary: '0 3px 0 rgba(122, 78, 43, 0.12)',
    cssVars: {
      '--jet-theme-stroke-width': '2px'
    }
  },
  illustration: {
    label: '插画风格',
    colorPrimary: '#625BFF',
    colorInfo: '#40A9FF',
    colorSuccess: '#36CFC9',
    colorWarning: '#FFB020',
    colorError: '#FF6B6B',
    colorBgBase: '#FBFCFF',
    colorBgLayout: '#F2F5FF',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#242235',
    colorText: '#242235',
    colorTextSecondary: '#6E6A85',
    colorBorder: '#DCE2FF',
    colorBorderSecondary: '#E9EDFF',
    borderRadius: 12,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    boxShadow: '0 12px 32px rgba(98, 91, 255, 0.12)',
    boxShadowSecondary: '0 6px 18px rgba(98, 91, 255, 0.10)'
  }
} satisfies Record<string, ThemeStyleToken>