import { DEFAULT_THEME_COLOR, normalizeThemeColor } from '@/utils/theme-color'
import theme from '@theme-config'
import type { ThemeStyleToken } from '@/utils/theme-style'

export const styleTokens = {
  'light': {
    label: '白色',
    colorPrimary: normalizeThemeColor(theme.colorPrimary) || DEFAULT_THEME_COLOR,
    colorInfo: '#1677FF',
    colorSuccess: '#52C41A',
    colorWarning: '#FAAD14',
    colorError: '#FF4D4F',
    colorBgBase: '#FFFFFF',
    colorBgLayout: '#F5F5F5',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#000000',
    colorText: 'rgba(0, 0, 0, 0.88)',
    colorTextSecondary: 'rgba(0, 0, 0, 0.65)',
    colorBorder: '#D9D9D9',
    colorBorderSecondary: '#F0F0F0',
    borderRadius: Number(theme.borderRadius) || 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    boxShadow: '0 6px 16px 0 rgba(0, 0, 0, 0.08)',
    boxShadowSecondary: '0 2px 8px rgba(0, 0, 0, 0.06)'
  },
  dark: {
    label: '黑色',
    colorPrimary: '#69B1FF',
    colorInfo: '#69B1FF',
    colorSuccess: '#49AA19',
    colorWarning: '#D89614',
    colorError: '#DC4446',
    colorBgBase: '#141414',
    colorBgLayout: '#000000',
    colorBgContainer: '#1F1F1F',
    colorBgElevated: '#262626',
    colorTextBase: '#FFFFFF',
    colorText: 'rgba(255, 255, 255, 0.88)',
    colorTextSecondary: 'rgba(255, 255, 255, 0.65)',
    colorBorder: '#424242',
    colorBorderSecondary: '#303030',
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.45)',
    boxShadowSecondary: '0 2px 8px rgba(0, 0, 0, 0.35)'
  },
  mui: {
    label: 'MUI 风格',
    colorPrimary: '#1976D2',
    colorInfo: '#0288D1',
    colorSuccess: '#2E7D32',
    colorWarning: '#ED6C02',
    colorError: '#D32F2F',
    colorBgBase: '#FFFFFF',
    colorBgLayout: '#F4F6F8',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#1D1D1F',
    colorText: 'rgba(0, 0, 0, 0.87)',
    colorTextSecondary: 'rgba(0, 0, 0, 0.6)',
    colorBorder: 'rgba(0, 0, 0, 0.12)',
    colorBorderSecondary: 'rgba(0, 0, 0, 0.08)',
    borderRadius: 4,
    borderRadiusLG: 6,
    borderRadiusSM: 3,
    boxShadow: '0 3px 6px rgba(0, 0, 0, 0.16)',
    boxShadowSecondary: '0 1px 3px rgba(0, 0, 0, 0.12)',
  },
  cartoon: {
    label: '卡通风格',
    colorPrimary: '#FF7A45',
    colorInfo: '#36CFC9',
    colorSuccess: '#73D13D',
    colorWarning: '#FFC53D',
    colorError: '#FF4D4F',
    colorBgBase: '#FFF7E6',
    colorBgLayout: '#FFF1D6',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#332018',
    colorText: '#332018',
    colorTextSecondary: '#7A4E2B',
    colorBorder: '#FFD591',
    colorBorderSecondary: '#FFE7BA',
    borderRadius: 14,
    borderRadiusLG: 18,
    borderRadiusSM: 10,
    boxShadow: '0 6px 0 rgba(122, 78, 43, 0.16)',
    boxShadowSecondary: '0 3px 0 rgba(122, 78, 43, 0.12)',
    cssVars: {
      '--jet-theme-stroke-width': '2px'
    }
  },
  illustration: {
    label: '插画风格',
    colorPrimary: '#625BFF',
    colorInfo: '#40A9FF',
    colorSuccess: '#36CFC9',
    colorWarning: '#FFB020',
    colorError: '#FF6B6B',
    colorBgBase: '#FBFCFF',
    colorBgLayout: '#F2F5FF',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#242235',
    colorText: '#242235',
    colorTextSecondary: '#6E6A85',
    colorBorder: '#DCE2FF',
    colorBorderSecondary: '#E9EDFF',
    borderRadius: 12,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    boxShadow: '0 12px 32px rgba(98, 91, 255, 0.12)',
    boxShadowSecondary: '0 6px 18px rgba(98, 91, 255, 0.10)'
  },
  ai: {
    label: 'AI风格',
    colorPrimary: '#2C4A7C',
    colorInfo: '#3E5A78',
    colorSuccess: '#4A6B48',
    colorWarning: '#8A6B2A',
    colorError: '#8A3A3A',
    colorBgBase: '#FFFFFF',
    colorBgLayout: '#F6F7F9',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorTextBase: '#1D1F24',
    colorText: '#1D1F24',
    colorTextSecondary: '#525560',
    colorBorder: '#E6E7EB',
    colorBorderSecondary: '#D2D4DA',
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.06), 0 0 0 1px rgba(0, 0, 0, 0.04)',
    boxShadowSecondary: '0 1px 2px rgba(0, 0, 0, 0.04), 0 0 0 1px rgba(0, 0, 0, 0.02)',
    layout: {
      menuVariant: 'compact-search',
      showMenuSearch: true,
      siderWidth: 224
    },
    cssVars: {
      '--canvas': '#F6F7F9',
      '--bg': '#FFFFFF',
      '--bg-elev': '#FFFFFF',
      '--bg-sunken': '#F1F2F4',
      '--bg-hover': '#EAECEF',
      '--line': '#E6E7EB',
      '--line-strong': '#D2D4DA',
      '--ink-1': '#1D1F24',
      '--ink-2': '#525560',
      '--ink-3': '#888C95',
      '--ink-4': '#B4B7BF',
      '--accent': 'var(--jet-theme-primary)',
      '--accent-ink': '#FFFFFF',
      '--accent-soft': 'var(--jet-theme-primary-soft)',
      '--jet-theme-stroke-width': '1px',
      '--chrome-bg': 'var(--bg)',
      '--chrome-elev': 'var(--bg-elev)',
      '--chrome-sunken': 'var(--bg-sunken)',
      '--chrome-hover': 'var(--bg-hover)',
      '--chrome-line': 'var(--line)',
      '--chrome-line-strong': 'var(--line-strong)',
      '--chrome-ink-1': 'var(--ink-1)',
      '--chrome-ink-2': 'var(--ink-2)',
      '--chrome-ink-3': 'var(--ink-3)',
      '--chrome-ink-4': 'var(--ink-4)',
      '--chrome-active-bg': 'transparent',
      '--chrome-active-ink': 'var(--chrome-ink-1)',
      '--chrome-active-line': 'var(--accent)',
      '--brand-mark-bg': 'var(--ink-1)',
      '--brand-mark-ink': 'var(--bg-elev)',
      '--chrome-nav-font-size': 'var(--fs-13)',
      '--chrome-nav-font-weight': '400',
      '--chrome-active-font-weight': '500',
      '--chrome-brand-font-weight': '600',
      '--chrome-label-font-weight': '600',
      '--chrome-control-radius': 'var(--r-2)',
      '--chrome-popover-radius': 'var(--r-3)',
      '--ok': '#4A6B48',
      '--ok-bg': '#EEF0E9',
      '--ok-line': '#D9E0D3',
      '--warn': '#8A6B2A',
      '--warn-bg': '#F4EDE0',
      '--warn-line': '#E6D9BD',
      '--err': '#8A3A3A',
      '--err-bg': '#F1E6E3',
      '--err-line': '#E4D0CC',
      '--info': '#3E5A78',
      '--info-bg': '#E9EDF2',
      '--info-line': '#D8E0E9',
      '--font-sans': 'AliRegular',
      '--font-cjk': 'AliRegular',
      '--font-mono': 'AliRegular',
      '--lh-tight': '1.15',
      '--lh-snug': '1.35',
      '--lh-normal': '1.5',
      '--lh-relaxed': '1.65',
      '--lh-loose': '1.8',
      '--fs-9': '9px',
      '--fs-9-5': '9.5px',
      '--fs-10': '10px',
      '--fs-10-5': '10.5px',
      '--fs-11': '11px',
      '--fs-11-5': '11.5px',
      '--fs-12': '12px',
      '--fs-12-5': '12.5px',
      '--fs-13': '13px',
      '--fs-13-5': '13.5px',
      '--fs-14': '14px',
      '--fs-15': '15px',
      '--fs-16': '16px',
      '--fs-17': '17px',
      '--fs-18': '18px',
      '--fs-19': '19px',
      '--fs-20': '20px',
      '--fs-22': '22px',
      '--fs-24': '24px',
      '--fs-26': '26px',
      '--fs-28': '28px',
      '--fs-tiny': 'var(--fs-9-5)',
      '--fs-pill': 'var(--fs-10-5)',
      '--fs-meta': 'var(--fs-11)',
      '--fs-body': 'var(--fs-12)',
      '--fs-label': 'var(--fs-13)',
      '--fs-h4': 'var(--fs-14)',
      '--fs-h3': 'var(--fs-16)',
      '--fs-h2': 'var(--fs-18)',
      '--fs-h1': 'var(--fs-22)',
      '--fs-display': 'var(--fs-26)',
      '--space-1': '2px',
      '--space-2': '4px',
      '--space-3': '6px',
      '--space-4': '8px',
      '--space-5': '10px',
      '--space-6': '12px',
      '--space-7': '14px',
      '--space-8': '16px',
      '--space-9': '20px',
      '--space-10': '24px',
      '--space-11': '32px',
      '--space-12': '40px',
      '--space-13': '48px',
      '--space-section': '64px',
      '--space-page': '96px',
      '--space-gutter': 'clamp(20px, 2.2vw, 48px)',
      '--r-1': '4px',
      '--r-2': '6px',
      '--r-3': '8px',
      '--r-4': '10px',
      '--shadow-1': '0 1px 0 rgba(0, 0, 0, 0.03)',
      '--shadow-2': '0 1px 2px rgba(0, 0, 0, 0.04), 0 0 0 1px rgba(0, 0, 0, 0.02)',
      '--shadow-pop': '0 4px 12px rgba(0, 0, 0, 0.06), 0 0 0 1px rgba(0, 0, 0, 0.04)',
      '--shadow-hover': '0 2px 8px rgba(0, 0, 0, 0.06)',
      '--shadow-lifted': '0 6px 20px rgba(0, 0, 0, 0.06)',
      '--ring-focus': '0 0 0 3px var(--accent-soft)',
      '--ring-active': '0 0 0 2px var(--accent-soft)',
      '--ring-ok': '0 0 0 3px var(--ok-bg)',
      '--ring-warn': '0 0 0 3px var(--warn-bg)',
      '--ring-err': '0 0 0 3px var(--err-bg)',
      '--ring-info': '0 0 0 3px var(--info-bg)',
      '--shadow-sticky-top': '0 -4px 12px rgba(0, 0, 0, 0.04)',
      '--shadow-fab': '0 6px 16px rgba(0, 0, 0, 0.12), 0 2px 6px rgba(0, 0, 0, 0.08)',
      '--z-dev-tools': '9999',
      '--ind-rail': 'var(--ink-1)',
      '--ind-rail-banner': 'var(--bg-sunken)',
      '--ind-rail-mark': 'var(--accent-soft)',
      '--ind-fuel': 'var(--ink-1)',
      '--ind-fuel-banner': 'var(--bg-sunken)',
      '--ind-fuel-mark': 'var(--accent-soft)',
      '--ind-park': 'var(--ink-1)',
      '--ind-park-banner': 'var(--bg-sunken)',
      '--ind-park-mark': 'var(--accent-soft)',
      '--ind-care': 'var(--ink-1)',
      '--ind-care-banner': 'var(--bg-sunken)',
      '--ind-care-mark': 'var(--accent-soft)',
      '--ind-industry': 'var(--ink-1)',
      '--ind-industry-banner': 'var(--bg-sunken)',
      '--ind-industry-mark': 'var(--accent-soft)',
      '--ind-safety': 'var(--ink-1)',
      '--ind-safety-banner': 'var(--bg-sunken)',
      '--ind-safety-mark': 'var(--accent-soft)',
      '--ind-energy': 'var(--ink-1)',
      '--ind-energy-banner': 'var(--bg-sunken)',
      '--ind-energy-mark': 'var(--accent-soft)',
      '--ind-general': 'var(--ink-2)',
      '--ind-general-banner': 'var(--bg-sunken)',
      '--ind-general-mark': 'var(--bg-sunken)',
      '--cp-scene': 'var(--ink-1)',
      '--cp-scene-bg': 'var(--accent-soft)',
      '--cp-protocol': 'var(--ink-1)',
      '--cp-protocol-bg': 'var(--accent-soft)',
      '--cp-skill': 'var(--ink-1)',
      '--cp-skill-bg': 'var(--accent-soft)',
      '--cp-screen': 'var(--ink-1)',
      '--cp-screen-bg': 'var(--accent-soft)',
      '--cp-kb': 'var(--ink-2)',
      '--cp-kb-bg': 'var(--bg-sunken)',
      '--cap-scene-pack': 'var(--ink-1)',
      '--cap-scene-pack-bg': 'var(--accent-soft)',
      '--cap-device': 'var(--ink-1)',
      '--cap-device-bg': 'var(--accent-soft)',
      '--cap-screen': 'var(--ink-1)',
      '--cap-screen-bg': 'var(--accent-soft)',
      '--cap-agent': 'var(--ink-1)',
      '--cap-agent-bg': 'var(--accent-soft)',
      '--cap-vision': 'var(--ink-1)',
      '--cap-vision-bg': 'var(--accent-soft)',
      '--cap-skill': 'var(--ink-1)',
      '--cap-skill-bg': 'var(--accent-soft)',
      '--ambient-hero': 'linear-gradient(135deg, #eef4ff, #f5f3ff, #fdf2f8)',
      '--ambient-cool': 'linear-gradient(135deg, #eef4ff, #f5f3ff)',
      '--ambient-warm': 'linear-gradient(135deg, #f5f3ff, #fdf2f8)',
      '--code-dark-bg': '#0F172A',
      '--code-dark-fg-1': '#E2E8F0',
      '--code-dark-fg-2': '#CBD5E1',
      '--code-dark-fg-3': '#94A3B8',
      '--code-dark-line': 'rgb(255 255 255 / 0.06)',
      '--code-dark-hover': 'rgb(255 255 255 / 0.08)',
      '--topbar-h': '48px',
      '--sidebar-w': '236px',
      '--row-h': '36px',
      '--pad-y': '8px',
      '--layout-menu-bg': '#FFFFFF',
      '--layout-menu-padding': '8px 10px',
      '--layout-menu-item-height': '32px',
      '--layout-menu-item-radius': '6px',
      '--layout-menu-item-active-bg': '#F1F2F4',
      '--layout-menu-item-active-color': 'var(--jet-theme-primary)',
      '--layout-menu-item-active-line': 'var(--jet-theme-primary)',
      '--layout-menu-search-bg': '#F6F7F9',
      '--layout-menu-search-border': '#E6E7EB'
    }
  }
} satisfies Record<string, ThemeStyleToken>
